include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:

  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a error (not a hint)
    missing_return: error
    parameter_assignments: warning
    # Custom for PaxSky only
    todo: ignore
    omit_local_variable_types: ignore
    unnecessary_this: ignore
    # DEV only -> Prod must remove
    unused_import: ignore
    sort_constructors_first: ignore

linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - empty_constructor_bodies
    - annotate_overrides
    - avoid_init_to_null
    - constant_identifier_names
    - one_member_abstracts
    - slash_for_doc_comments
    # - sort_constructors_first
    - unnecessary_brace_in_string_interps